# Generated by Django 6.1 on 2026-09-02 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-label'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Mixed', 'Mixed')], default='Mixed', max_length=10)),
                ('default_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['name', 'gender'],
                'unique_together': {('code', 'gender')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('roll_no', models.CharField(max_length=40, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('semester', models.CharField(blank=True, max_length=30)),
                ('default_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue'), ('Partial', 'Partial'), ('Partial-Overdue', 'Partial-Overdue')], default='Pending', max_length=20)),
                ('contact', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.academicyear')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.schoolclass')),
            ],
            options={
                'ordering': ['roll_no'],
            },
        ),
        migrations.CreateModel(
            name='TransportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Paused', 'Paused'), ('Stopped', 'Stopped')], max_length=10)),
                ('from_label', models.CharField(blank=True, max_length=40)),
                ('until_label', models.CharField(blank=True, max_length=40)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('set_on', models.DateField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_status', to='academics.student')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.schoolclass')),
            ],
            options={
                'ordering': ['school_class', 'name'],
                'unique_together': {('school_class', 'name')},
            },
        ),
    ]
