# Generated by Django 5.2.17 on 2026-09-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sch_mode',
            field=models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='sch_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='sch_type',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='sch_val',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
