# Generated by Django 6.1 on 2026-09-02 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('color', models.CharField(blank=True, max_length=10)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Expense categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_name', models.CharField(default='Superior College', max_length=200)),
                ('city', models.CharField(default='Lahore', max_length=100)),
                ('academic_year_label', models.CharField(default='2024–25', max_length=20)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('late_fee_pct', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('fee_due_day', models.PositiveIntegerField(default=25)),
                ('session_timeout_min', models.PositiveIntegerField(default=15)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('bank_branch', models.CharField(blank=True, max_length=150)),
                ('bank_account_title', models.CharField(blank=True, max_length=150)),
                ('bank_account_no', models.CharField(blank=True, max_length=50)),
                ('bank_iban', models.CharField(blank=True, max_length=50)),
                ('bank_jazzcash', models.CharField(blank=True, max_length=30)),
                ('bank_easypaisa', models.CharField(blank=True, max_length=30)),
                ('accounts_phone', models.CharField(blank=True, max_length=30)),
                ('office_hours', models.CharField(blank=True, max_length=100)),
                ('customer_code', models.CharField(blank=True, max_length=10)),
                ('voucher_prefix', models.CharField(default='FEE', max_length=10)),
                ('voucher_instructions', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Institution settings',
                'verbose_name_plural': 'Institution settings',
            },
        ),
        migrations.CreateModel(
            name='ManualTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('vehicle_no', models.CharField(blank=True, max_length=30)),
                ('driver_name', models.CharField(blank=True, max_length=150)),
                ('driver_phone', models.CharField(blank=True, max_length=30)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('fitness_expiry', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['route_id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('approver', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Approved', max_length=20)),
                ('tx_seq', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='academics.academicyear')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('semester', models.CharField(blank=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('category', models.CharField(choices=[('Tuition', 'Tuition'), ('Admission', 'Admission'), ('Transport', 'Transport'), ('Other', 'Other')], default='Tuition', max_length=20)),
                ('method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Bank', 'Bank'), ('JazzCash', 'JazzCash'), ('EasyPaisa', 'EasyPaisa'), ('Cheque', 'Cheque')], max_length=20)),
                ('receipt_no', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue'), ('Partial', 'Partial'), ('Partial-Overdue', 'Partial-Overdue')], default='Pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('is_installment', models.BooleanField(default=False)),
                ('installment_part', models.PositiveIntegerField(blank=True, null=True)),
                ('installment_total', models.PositiveIntegerField(blank=True, null=True)),
                ('plan_id', models.CharField(blank=True, max_length=40)),
                ('tx_seq', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='academics.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='academics.student')),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Bank', 'Bank'), ('JazzCash', 'JazzCash'), ('EasyPaisa', 'EasyPaisa'), ('Cheque', 'Cheque')], max_length=20)),
                ('receipt_no', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.fee')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='academics.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TransportFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Bank', 'Bank'), ('JazzCash', 'JazzCash'), ('EasyPaisa', 'EasyPaisa'), ('Cheque', 'Cheque')], max_length=20)),
                ('receipt_no', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue'), ('Partial', 'Partial'), ('Partial-Overdue', 'Partial-Overdue')], default='Pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('tx_seq', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_fees', to='academics.academicyear')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_fees', to='finance.route')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_fees', to='academics.student')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='TransportFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Bank', 'Bank'), ('JazzCash', 'JazzCash'), ('EasyPaisa', 'EasyPaisa'), ('Cheque', 'Cheque')], max_length=20)),
                ('receipt_no', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transport_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.transportfee')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=150)),
                ('allocated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='academics.academicyear')),
                ('expense_categories', models.ManyToManyField(blank=True, related_name='budgets', to='finance.expensecategory')),
            ],
            options={
                'ordering': ['department'],
                'unique_together': {('department', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sal_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('month', models.CharField(max_length=30)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('tx_seq', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='hr.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
